import { Brain, Sparkles } from "lucide-react";

import { useAiRecommendations } from "@/hooks/queries/useAuthorityQueries";
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { StatusChip } from "@/components/ui/status-chip";
import { DataText, Muted } from "@/components/ui/typography";
import { ListCardSkeleton } from "@/components/common/skeletons";
import ErrorState from "@/components/common/ErrorState";
import { toast } from "@/hooks/use-toast";

/**
 * PLACEHOLDER: styled as IBM Watson output. Recommendations now load
 * from the API (useAiRecommendations); "Apply" still just confirms via
 * toast — no action-execution endpoint exists for this yet.
 */
function AIRecommendations() {
  const { data: recommendations, isLoading, isError, error, refetch, isRefetching } = useAiRecommendations();

  function handleApply(title) {
    toast({ title: "Suggestion queued", description: title });
  }

  if (isLoading) return <ListCardSkeleton rows={3} />;

  return (
    <Card variant="highlight">
      <CardHeader className="flex-row items-center justify-between space-y-0">
        <div>
          <CardTitle>AI recommendations</CardTitle>
          <CardDescription>Generated by IBM Watson — preview only</CardDescription>
        </div>
        <Brain className="size-4 text-muted-foreground" />
      </CardHeader>

      {isError ? (
        <CardContent>
          <ErrorState context="AI recommendations" detail={error?.message} onRetry={refetch} retrying={isRefetching} />
        </CardContent>
      ) : recommendations.length === 0 ? (
        <CardContent>
          <Muted>No recommendations right now.</Muted>
        </CardContent>
      ) : (
        <CardContent className="divide-y divide-border p-0">
          {recommendations.map((rec) => (
            <div key={rec.id} className="flex items-start gap-3 p-3.5">
              <Sparkles className="mt-0.5 size-4 shrink-0 text-muted-foreground" />
              <div className="min-w-0 flex-1">
                <div className="text-sm font-medium text-foreground">{rec.title}</div>
                <Muted className="mt-1">{rec.detail}</Muted>
                <div className="mt-2 flex items-center gap-2">
                  <StatusChip variant="primary" dot={false}>
                    <DataText className="text-2xs">{rec.confidence}% confidence</DataText>
                  </StatusChip>
                  <Button size="sm" variant="outline" onClick={() => handleApply(rec.title)}>
                    Apply suggestion
                  </Button>
                </div>
              </div>
            </div>
          ))}
        </CardContent>
      )}
    </Card>
  );
}

export default AIRecommendations;
