import { Brain } from "lucide-react";

import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card";
import { StatusChip } from "@/components/ui/status-chip";
import { DataText, Muted } from "@/components/ui/typography";

/**
 * PLACEHOLDER: static, illustrative reasoning styled as IBM Watson
 * output. No model is actually queried here — this demonstrates the
 * intended UI for when severity-explanation is wired to a real model.
 */
function AIExplanation({ aiExplanation }) {
  return (
    <Card variant="highlight" className="h-full">
      <CardHeader className="flex-row items-center justify-between space-y-0">
        <div>
          <CardTitle>AI explanation</CardTitle>
          <CardDescription>Generated by IBM Watson — preview only</CardDescription>
        </div>
        <Brain className="size-4 text-muted-foreground" />
      </CardHeader>
      <CardContent className="space-y-4">
        <p className="text-sm leading-relaxed text-foreground/90">{aiExplanation.summary}</p>

        <div className="space-y-2.5">
          {aiExplanation.signals.map((s) => (
            <div key={s.label}>
              <div className="mb-1 flex items-center justify-between text-xs">
                <span className="font-medium text-foreground">{s.label}</span>
                <DataText className="text-muted-foreground">{s.weight}%</DataText>
              </div>
              <div className="h-1.5 w-full overflow-hidden rounded-full bg-muted">
                <div
                  className="h-full rounded-full bg-primary transition-all"
                  style={{ width: `${s.weight}%` }}
                />
              </div>
              {s.detail && <Muted className="mt-1">{s.detail}</Muted>}
            </div>
          ))}
        </div>

        <div className="flex items-center justify-between border-t border-border pt-3">
          <Muted>Overall confidence</Muted>
          <StatusChip variant="primary" dot={false}>
            {aiExplanation.confidence}%
          </StatusChip>
        </div>
      </CardContent>
    </Card>
  );
}

export default AIExplanation;
