/**
 * models/RiskZone.model.js
 * Block-level risk unit produced by the CV/Graph AI/time-series pipeline.
 * `riskLevel` is derived from `riskScore` on save so callers never have
 * to keep the two in sync manually.
 */

const mongoose = require('mongoose');
const geoPolygonSchema = require('./schemas/geoPolygon.schema');

const HAZARD_TYPES = ['flood', 'fire', 'structural', 'landslide', 'other'];
const RISK_LEVELS = ['low', 'moderate', 'high', 'critical'];
const DATA_SOURCES = ['satellite', 'citizen_report', 'historical', 'manual', 'agent_reassessment'];

const riskZoneSchema = new mongoose.Schema(
  {
    blockId: {
      type: String,
      required: [true, 'blockId is required'],
      unique: true,
      trim: true,
      uppercase: true,
    },
    name: {
      type: String,
      trim: true,
      maxlength: 150,
    },
    settlement: {
      type: String,
      required: [true, 'settlement is required'],
      trim: true,
      maxlength: 150,
    },
    geometry: {
      type: geoPolygonSchema,
      required: true,
    },
    hazardType: {
      type: String,
      enum: HAZARD_TYPES,
      required: true,
    },
    riskScore: {
      type: Number,
      required: true,
      min: 0,
      max: 100,
    },
    riskLevel: {
      type: String,
      enum: RISK_LEVELS,
      // derived in pre-save hook from riskScore; not required on input
    },
    confidence: {
      type: Number,
      min: 0,
      max: 1,
      required: true,
    },
    contributingFactors: {
      type: [
        {
          _id: false,
          factor: { type: String, required: true, trim: true },
          weight: { type: Number, required: true, min: 0, max: 1 },
        },
      ],
      default: [],
      validate: {
        validator: (arr) => arr.length <= 20,
        message: 'contributingFactors cannot exceed 20 entries',
      },
    },
    populationEstimate: {
      type: Number,
      min: 0,
    },
    dataSource: {
      type: String,
      enum: DATA_SOURCES,
      required: true,
      default: 'satellite',
    },
    lastAnalyzedAt: {
      type: Date,
      default: Date.now,
    },
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      default: null, // null when generated by the automated pipeline, not a human
    },
  },
  { timestamps: true }
);

// ---- Indexes ----
// blockId uniqueness is already declared inline above.
riskZoneSchema.index({ geometry: '2dsphere' });
riskZoneSchema.index({ riskLevel: 1, riskScore: -1 });
riskZoneSchema.index({ settlement: 1 });

// ---- Hooks ----
riskZoneSchema.pre('save', function deriveRiskLevel(next) {
  if (this.isModified('riskScore')) {
    if (this.riskScore >= 80) this.riskLevel = 'critical';
    else if (this.riskScore >= 60) this.riskLevel = 'high';
    else if (this.riskScore >= 30) this.riskLevel = 'moderate';
    else this.riskLevel = 'low';
  }
  next();
});

module.exports = mongoose.model('RiskZone', riskZoneSchema);
module.exports.HAZARD_TYPES = HAZARD_TYPES;
module.exports.RISK_LEVELS = RISK_LEVELS;
