/**
 * models/Task.model.js
 * A relief task posted against an Incident and (optionally) claimed by a
 * Volunteer — this is the "task marketplace" that turns the dashboard from
 * read-only into operational.
 */

const mongoose = require('mongoose');
const geoPointSchema = require('./schemas/geoPoint.schema');
const { SKILLS } = require('./Volunteer.model');

const TASK_TYPES = [
  'evacuation_assist',
  'medical',
  'logistics',
  'drainage_clearance',
  'damage_assessment',
  'other',
];
const PRIORITIES = ['low', 'medium', 'high', 'critical'];
const STATUSES = ['open', 'assigned', 'in_progress', 'completed', 'cancelled'];

const taskSchema = new mongoose.Schema(
  {
    title: {
      type: String,
      required: [true, 'title is required'],
      trim: true,
      maxlength: 200,
    },
    description: {
      type: String,
      trim: true,
      maxlength: 1000,
    },
    incident: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Incident',
      required: [true, 'incident is required'],
    },
    riskZone: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'RiskZone',
      default: null,
    },
    taskType: {
      type: String,
      enum: TASK_TYPES,
      required: true,
    },
    priority: {
      type: String,
      enum: PRIORITIES,
      default: 'medium',
    },
    status: {
      type: String,
      enum: STATUSES,
      default: 'open',
    },
    requiredSkills: {
      type: [{ type: String, enum: SKILLS }],
      default: [],
    },
    location: {
      type: geoPointSchema,
      required: true,
    },
    createdByAuthority: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Authority',
      default: null, // null when auto-generated by the Volunteer Coordinator agent
    },
    assignedVolunteer: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Volunteer',
      default: null,
    },
    estimatedTimeMinutes: {
      type: Number,
      min: 0,
    },
    acceptedAt: { type: Date, default: null },
    startedAt: { type: Date, default: null },
    completedAt: { type: Date, default: null },
  },
  { timestamps: true }
);

// ---- Indexes ----
taskSchema.index({ status: 1, priority: -1 });
taskSchema.index({ assignedVolunteer: 1, status: 1 });
taskSchema.index({ incident: 1 });
taskSchema.index({ location: '2dsphere' });

// ---- Validation ----
taskSchema.pre('validate', function requireAssigneeWhenAssigned(next) {
  if (this.status !== 'open' && !this.assignedVolunteer) {
    return next(new Error(`assignedVolunteer is required when status is "${this.status}"`));
  }
  next();
});

module.exports = mongoose.model('Task', taskSchema);
module.exports.TASK_TYPES = TASK_TYPES;
module.exports.PRIORITIES = PRIORITIES;
module.exports.STATUSES = STATUSES;
